spring.application.name=hubstudentesc

server.port=8088

spring.datasource.url=jdbc:postgresql://localhost:5432/hubstudentesc
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=auth

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true