spring.application.name=hubstudentesc

server.port=8088

spring.datasource.url=jdbc:postgresql://localhost:5432/hubstudentesc
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=app_auth

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

azure.storage.connection-string=${AZURE_STORAGE_CONNECTION_STRING}
azure.storage.container-name=post-media
azure.storage.marketplace-container-name=marketplace-materials

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}

jwt.secret=hubstudenti-super-secret-key-for-jwt-authentication-2026
jwt.expiration=3600000
